### ISSUE TITLE
Finalizar slides sobre o desenvolvimento do game

### ISSUE THREAD

**Issue by Danielll-Santos** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-program_acao_#23]

**Comment by leobronks** [comment]
Com a ajuda do @Washington-Freitas, estamos criando um slide com o passo a passo de um modelo de jogo.
Entretanto, esta é uma base para que eles possam desenvolver sua criatividade e assim criar o seu próprio jogo.
