### ISSUE TITLE
Gravação do conteúdo

### ISSUE THREAD

**Issue by Danielll-Santos** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-program_acao_#24]
Gravação de videoaulas sobre os temas:
- As profissões voltadas à Computação no Mercado de Trabalho;
- Aspectos teóricos no desenvolvimento de um jogo eletrônico;
- Desenvolvimento de um jogo usando a ferramenta online GDevelop 5.

**Comment by leobronks** [comment]
Está etapa foi cancelada pois os alunos conseguiram vir, então serão feitas aulas no Prédio 1 da Puc MInas de Poços de Caldas. 
As mesmas começaram no dia 21/11/2024 as 14 horas e terão continuidade no dia 28/11/2024 e 05/12/2024, no mesmo horário já inserido neste informativo.
