### ISSUE TITLE
Aula 1 - Introdução, a Computação e o Mercado de Trabalho, aspectos teóricos do desenvolvimento de games

### ISSUE THREAD

**Issue by Danielll-Santos** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-program_acao_#25]

**Comment by leobronks** [comment]
Dia 21 de novembro ouve a primeira apresentação do grupo no laboratóriio, foi se apresentando para 5 alunos.
Os temas que foram mostrados, são a introdução da computaçao em relação a games, o tipos de games, coisas boas e ruins que os jogos podem trazer, as profissões que são mais buscadas para o mercado de trabalho....

**Comment by leobronks** [comment]
Colaboradores que apresentaram no dia 21 de novembro: @Danielll-Santos , @VisionedGu e @leonardosilvamelosantos.
